general:
  label: 基本设置
  items:
    subtitle:
      name: subtitle
      label: 副标题
      type: text
    welcome_message:
      name: welcome_message
      label: 欢迎信息
      type: text
    cover_image:
      name: cover_image
      label: 首页背景图片
      type: attachment
    cover_color:
      name: cover_color
      label: 首页背景颜色
      type: select
      default: 'red'
      options:
        - value: blue
          label: blue
        - value: green
          label: green
        - value: purple
          label: purple
        - value: red
          label: red
        - value: orange
          label: orange
        - value: slate
          label: slate
        - value: empty
          label: 空
    blog_button_title:
      name: blog_button_title
      label: 博客按钮名称
      type: text
      default: 'Blog'
    blog_button_description:
      name: blog_button_description
      label: 博客按钮描述
      type: text
      default: 'Visit blog'
sns:
  label: 社交资料设置
  items:
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    weibo:
      name: weibo
      label: 微博
      type: text
    github:
      name: github
      label: GitHub 链接
      type: text
    google_plus:
      name: google_plus
      label: Google Plus
      type: text
    email:
      name: email
      label: Email
      type: text
